# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias baj='ns:baj'
alias asjs='baj:asjs'
alias dist='baj:dist'
alias header='baj:header'
alias emit='baj:emit'
alias bm4='baj:bm4'
alias mk-alias='baj:mk-alias'
alias main='baj:main'
baj:asjs () 
{ 
    if test -v Y2J_USE_PYTHON; then
        python3 -c 'import sys, yaml, json; print(json.dumps(yaml.safe_load(sys.stdin.read())))';
    else
        yq -oj "$@";
    fi
}
baj:bm4 () 
{ 
    local jq='def head: "m4_changequote(«,»)m4_changecom()m4_dnl";
def m4: .[][] | to_entries[] | "m4_define(«\(.key)»,«\(.value | @json[1:-1])»)m4_dnl";
def main: if map(has("m4")) | any then group_by(has("m4")) | (last | m4), first end;
head, (inputs | main)';
    jq -nr "$jq" | m4 -P
}
baj:clean () 
{ 
    local ns=${FUNCNAME%%:*};
    local i;
    for i in ${BASH_ALIASES[@]/$ns:clean};
    do
        if [[ $i =~ ${1:?}: ]]; then
            unalias "${i/$ns:}";
        fi;
    done;
    for i in $(compgen -c $1);
    do
        unset $i;
    done
}
baj:dist () 
{ 
    local jq='def isa:
  def isa:
    if .[1] | not then "alien"
    elif (first | IN("array", "null")) and last == 0 then "root"
    elif first == "array" then "sup"
    else "sub" end;
  def addIsa: has("id") as $id | (.id | [type, $id, length] | isa) as $isa | . + { $isa };
  map(addIsa) | group_by(.isa) | map({ (first.isa): map(del(.isa)) }) | add
  | reduce ("root", "sup") as $i (.; if has($i) | not then .[$i] = [{ id: []}] end);

def useindex: "i";
def addindex: to_entries | map(.value + { (useindex): .key });
def remindex: sort_by(.[useindex]) | map(del(.[useindex]));

def sameType(t): (map(type) | unique) == [t | type];
# merge list of object [ o, ... ]
def merge:
  # merge two objects [ o1, o2 ]
  def merge:
    # merge two values [ v1, v2 ]
    def merge:
      # First is sub, last is sup
      # add lists, sup <- sub otherwise
      if sameType([]) then add | unique else last end;
    # merge all sub values into sup ones
    reduce (first | to_entries)[] as $e (last; .[$e.key] = ([.[$e.key], $e.value] | merge));
  # merge all objects using merge two objects
  reduce .[] as $i ({}; [., $i] | merge);

def check:
  (.sup | map(.id) | add) - (.sub | keys) | unique
  | if length > 0 then "bad id \(@json)\n" | halt_error(1) else empty end;

def main:
  addindex | isa | .sub |= INDEX(.[]; .id)
  | (.sub | keys) as $subs | .root |= map(.id = $subs) | .sub as $sub | .alien as $alien | check
  , reduce (.root + .sup)[] as $sup ($sub; reduce $sup.id[] as $id (.; .[$id] |= ([., ($sup | del(.id))] | merge)))
  | map(.) + $alien | remindex;

main';
    jq -r "$jq"
}
baj:emit () 
{ 
    local jq='def w($s): $s + . + $s;
def q: w("\u0027");
def qq: w("\"");
def at: "$@" | qq;
def at($n): "${@:\($n)}" | qq;

def is($is): has("is") and IN($is; .is[]);

def ky: map(select([has("ky", "is")] | all)) | map(map(.) | combinations);
def byky: ky | group_by(first) | map({ (first | first): map(last) }) | add;
def byis: ky | group_by(last) | map({ (first | last): map(first) }) | add;

def aliases:
  def fa: if is("fa") then " " else "" end | @sh;
  .in[] | select(has("id") and has("ns")) | "\($ns):mk-alias \(.id) \(.ns) \(fa)";

def noalias: .in[] | select(is("na")) | "unalias \(.id)";

def ns:
  .in | map(.ns) | unique[]
  | "alias \(.)=ns:\(.); ns:\(.) () { \(.):${1:?} \(at(2)); }";

def is_sh_var:
   def iterable: type | IN("array", "object");
.key != "js" and (.value | (iterable | not) or (map(.) | unique | map(iterable | not) | all));

def js_var: "local \(.key)=\(.value | @json | @sh)";
def sh_array_var: "local -a \(.key)=(\(.value | map(@sh) | join(" ")))";
def sh_map_var: .key as $k | .value | to_entries | map(map(@sh)[]) | join(" ") | "local -A \($k)=(\(.))";

def sh_var:
  (.value | type) as $t
  | if $t == "array" then sh_array_var
    elif $t == "object" then sh_map_var
    else "local \(.key)=\(.value | @sh)" end;

def var: if is_sh_var then sh_var else js_var end;
def novars($kys): (null | { sh, ns, id, is } | keys + $kys.nv) as $k | del(.[$k[]]);
def vars($kys): novars($kys) | to_entries | map(var);

def sh: .sh // "self \(at)";
def body($kys): vars($kys) + [sh | rtrimstr("\n")] | join("; ");

def funs:
  .kys as $kys
  | .in[] | select(has("id")) | "\(.ns):\(.id) () { \(body($kys)); }";

def src: .in | group_by(.ns) | map("\(first.ns):src () { <<< \(. | @json | @sh) jq; }")[];

{ in: ., kys: byis } | aliases, funs, ns, noalias, src';
    jq -r "$jq" --arg ns ${FUNCNAME%%:*}
}
baj:header () 
{ 
    echo shopt -s expand_aliases;
    declare -f ${FUNCNAME%%:*}:mk-alias
}
baj:init () 
{ 
    local ns=${FUNCNAME%%:*};
    $ns:header;
    $ns:asjs | $ns:dist | $ns:emit;
    echo unalias init clean
}
baj:main () 
{ 
    local ns=${FUNCNAME%%:*};
    $ns:header;
    $ns:asjs | $ns:bm4 | $ns:dist | $ns:emit
}
baj:mk-alias () 
{ 
    : ${2:?};
    local -n a=BASH_ALIASES;
    if [[ ! -v a[$1] || -v a[$1] && "${a[$1]}" == "$2:${1}$3" ]]; then
        alias $1="$2:${1}$3";
    else
        echo warning $(alias $1) not redefined as "'$2:${1}$3'" 1>&2;
    fi
}
baj:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA51Y/44btxH+v0/BqIq9W6/WvssBBXRWaqd1EBetG8AJ0GAlCJSWOlFacXXL1TmC
TnmhPEL+85P1myG5u9IpLVDAhkjuzMf5PcPLDj1je8PeTK56SU/ntNzcYLm6xzJXC7FUMh+KcW9z
M50vpblT97uyVtHnX5PPv8XN4bzcRLTLTTHu3Y4NcW5uhiLNJtlEPIq6nCpTV1pZ3jIcaLQhpPE4
StdqH3/+LXGbB1nsFMjerGxpsqvh4GoSu9tO8KU2Q6FpsY2W0kaEOu7FMTil2Yt6qYy4q8rddjrb
nxNEhbQ1fjc3cSIWusJGmRzIpG8iIm22u9oSAW6JYRC7hEFW92JgKojfX92Pe8wuBt/3jslTM+ba
1l07aiuHYyNEdy1I+jS7IpOYsnYSj3uy0MqMe45CFaCJnISP4v0HKCGrSu7HvQSkZlcUrJE0uWCV
RiPxKgBVZVmf4DgYkDQggdTuti2lVXwyw2dnFCe2zPP3kFw4U+ocFwtpRV/nZNCUf7J6v1UJnSWi
UOauXpJyUNiTWoltKl6Ig9scGZ086NDJN43PUu0O6PPBG4HPhnyUq8KRxOLITs9zAnsUlcp3cyWi
YIEkKOiFgLC3ZHpSpK/jrvXTrK8nYiSyg9CI+2xynJANYojpom5nlcbiZ8oJ3cQirvanbaR7wX00
k8ZRYIYCFPEQ2/NXauP5bVnVrHsWiCfBBKxv57gVysqN+gGGj2ogR0RLbiC+ndH3O6zg84wCiM4n
4Puj2KjqTokCYSrKhShnKzWvRSbKRKRpKiY+x4iIYzUw1J9KT2yJ+ioR5TVRuxBp6U852AbE8ACG
B8/wlIWYvuUY1VYgABMX07zZtiSwNgtuEzoXrwdEK0o4sPqkrQqEumOYDFZkBxNvMIsLdb4ixHkr
tiwKhvWia1OXfFtplHWUIcxCcrauj1HlKNKUqzO3FFaKPE6hFWXNDomiXHxQlvC97NVTKYK5d1ab
u6duIHIvSurvRYQfjrciSykTW+gmXuZLNV+zzaOUdPKRqnOfRrEY8JcZtpDTtpHkEgyWdcktvm6r
zUzmyBmBAs51Ox7jNqqRS1nUU1VVZRVdxc7karOt997mnWJO4CGTXNWgYsFijFD6/vbu34j/CawJ
QZ0gp0KS6thT5qWU+cTmFYPd+VMcED0tbbne8oFbPTr70A1J42QH+IKYt8G9ZLqIUG4DGR3htuCG
nCsN1ZR8QsJE5JGo70zuylcexx3fe7VY6Bi3NRKFAsEGI2N1W1LTkS52ImlXNlDDcbVCsA4exE/X
f5/++PHd9PuffvjuXx+Ay27c7utlab4Sg7l4rjdbFCNh98izvdwUiSC/3opthWSIaJ3mu83WRvQx
tXKhpkUp8wgMqa3hxrRCM42gVfwc+Oz5PcQtVyTvGxRPNKSLIm/WAyguG7GHon+4Hv7lODZFOZcF
mrCQo2/efvxu+vYf799+fPcR8FAty8QXpJrM+tRTH9v1s2d05YE3R0Qlt8D+9bB/uDr2v8LBZBIs
wBeL/tXohCDIr+bLUnySlaFU7EeBOOYOgiDgmSYn7497zxv+57jh62fXAPkdheHdk2nhE4IEpbxv
KeIoDqxvFPdDfEOnHu9evbr+MzpaOG8+4H9zKuuhNzVC6P6+OY36JuYvhzdD5Ct2x5bEEWlqjSSD
7/aWuyemDIwg+EBJiFmuLSnrvWvKVhUoSlHm2NZ+TmF2inPUszj0Mx/lSLdyM9NG1ro0Nog+2xPi
et+dB7jQng8E2Lpzdz/V23YeaMC0PQdzhE+w+NhB+es6WN5+5HRlm3FuIXkM1aTwQpKdfEWkf36a
cqMUzbR2yQU+1YZHYW+vk5kKhG5vrB9XybFwE/wRUoPqLBds+sUH+l3ImCPViWlKJhyeX8VyGtkg
78wJYBfB6Qj+UJNMpxVkE1eseGD1/PGIeGhxK8JKRDFmH15SOiCNaYMgvEavE8fOfdpO7XL6ICs3
DvBRrSo5K9SQJ5cLE7Brgi7keab6glJ7BcOxHdvHRBSg3LgXi7ISbQj6gcCpeU7pw7aRc2VZSNzj
ylF4wIyePF6cw+NmToR6LPsp/0C2EFEXg4QhfixXpTYRhxR1iQ4eaBwaa0/VaE1NLUA8mUcDZjY5
g2VXeoHekkD9tRcn7gZFx0OtoG7cpMvrZkLoX3ppdA3QeZgE2uDNhthrd/Iy+W9GZ2OfTBZsG90J
rgab1gzp/Om5XOpgjwK43lMFjOiVBfADmBKEdSLodYOh9OgnDyrQIE3NQ9w4wA3r/XU2mYSS1sXs
3nDJS/jaGe+X8K5dipcv6SGjioVLoDYMZmW+D8gd3BciAxeGByBvbF1xfzC+EnvP3wqXOw5osQs5
DwCny946j/5+wWoKFJWHYahLIetb2c6y3Vbzoa8t7YvPFRiyACO6Jx/BgtpBvn79mn1/lmJidc/w
iGu+Ae83A/gEVR8lkBoAu8vX7oQ1dc70dTIhgS5OVWIwkNUdaDGFfPvjh79+ePvPd19+OfzT8WIr
nxdKNtOZC1VjR2ecYZDRGIFQhzSEBXh3osneTF6i4A8ZDrN8Xgo34WC4H/0iXCEdYm5x4dwUcfR0
zYxHN18Rp8HY3l4Tod1u78CDGQ+TC0PDGKoGtKO+qBf9YURVQTGeg+yy3GKWtEL9vEWxnXrjAkTN
C1kpMVicm6zpXxfv0IbHoP9hOtLOSXMraE0DLlxLS/qri1/SSEXv3HWxo/dSKZY6p99SKGn3dDAv
i4LODB6JGO9Io2BGEkQ4T16cTzsD+P8l52xzc1ni3nHyh/8AbqAt3ZUTAAA=
' | zcat | jq
}
ns:baj () 
{ 
    baj:${1:?} "${@:2}"
}
ns:bajl () 
{ 
    bajl:${1:?} "${@:2}"
}
alias bajl='ns:bajl'
alias nsp='bajl:nsp'
alias md2js='bajl:md2js'
alias zsrc='bajl:zsrc'
alias forget='bajl:forget'
alias lib='bajl:lib'
alias nss='bajl:nss'
alias prudent='bajl:prudent'
alias map='bajl:map '
alias opts='bajl:opts'
alias ns='bajl:ns'
alias tst='bajl:tst'
alias aliases1='bajl:aliases1'
alias fn='bajl:fn'
alias list='bajl:list'
alias txt='bajl:txt'
alias ids='bajl:ids'
alias aliases='bajl:aliases'
alias yml2sh='bajl:yml2sh'
alias fail='bajl:fail'
alias def='bajl:def'
alias self='bajl:self'
alias as-lib='bajl:as-lib'
alias load='bajl:load'
alias listid='bajl:listid'
alias as-cmd='bajl:as-cmd'
alias with-lib='bajl:with-lib'
alias exp='bajl:exp'
alias loop='bajl:loop '
alias fns='bajl:fns'
alias args='bajl:args '
bajl:aliases () 
{ 
    bajl:loop bajl:aliases1 "$@"
}
bajl:aliases1 () 
{ 
    local jq='$ARGS.positional | [.[:$n], .[$n:]] | transpose[] | select(last | test("\($ns):")) | first';
    bajl:nsp ${1:?} || bajl:fail not a ns;
    bajl:self -nr --arg ns $1 --argjson n ${#BASH_ALIASES[@]} --args "${!BASH_ALIASES[@]}" "${BASH_ALIASES[@]}"
}
bajl:args () 
{ 
    mapfile -t;
    ((${#MAPFILE[@]} > 0)) && "${@:-echo}" "${MAPFILE[@]}"
}
bajl:as-cmd () 
{ 
    bajl:as-lib "$@";
    echo 'eval "$@"'
}
bajl:as-lib () 
{ 
    bajl:warn;
    bajl:lib "$@"
}
bajl:def () 
{ 
    bajl:loop bajl:def1 "$@"
}
bajl:def1 () 
{ 
    [[ -v BASH_ALIASES[${1:?}] ]] || bajl:fail $1 not an alias && declare -f ${BASH_ALIASES[$1]}
}
bajl:exp () 
{ 
    bajl:loop bajl:exp1 "$@"
}
bajl:exp1 () 
{ 
    bajl:listid ${1:?} | bajl:args echo export -f
}
bajl:fail () 
{ 
    unset -v fail;
    : "${fail:?${FUNCNAME[1]} $@}"
}
bajl:fn () 
{ 
    bajl:loop bajl:fn1 "$@"
}
bajl:fn1 () 
{ 
    bajl:listid1 ${1:?} | bajl:args declare -f
}
bajl:fns () 
{ 
    bajl:ids "$@" | bajl:args bajl:def
}
bajl:forget () 
{ 
    bajl:loop bajl:forget1 "$@"
}
bajl:forget1 () 
{ 
    . <(${FUNCNAME%%:*}:listid1 ${1:?} | args echo unset -f; nsp $1 && { aliases $1 | args echo unalias; echo unalias $1; })
}
bajl:ids () 
{ 
    bajl:loop bajl:ids1 "$@"
}
bajl:ids1 () 
{ 
    local jq='.[].id';
    eval ${1:?} src | jq "$jq" -r
}
bajl:lib () 
{ 
    bajl:optal;
    bajl:loop bajl:lib1 "$@";
    bajl:def self;
    bajl:exp "$@"
}
bajl:lib1 () 
{ 
    bajl:nsp ${1:?} || bajl:fail not a ns;
    alias $1;
    alias $(aliases $1);
    . <(zsrc $1);
    bajl:fn $1
}
bajl:list () 
{ 
    bajl:loop echo "$@"
}
bajl:listid () 
{ 
    bajl:loop bajl:listid1 "$@"
}
bajl:listid1 () 
{ 
    compgen -c ${1:?}:;
    compgen -c ns:${1:?}
}
bajl:load () 
{ 
    bajl:forget $(nss "$@");
    . <(${FUNCNAME%%:*}:txt "$@")
}
bajl:loop () 
{ 
    local i;
    for i in "${@:2}";
    do
        $1 "$i";
    done
}
bajl:map () 
{ 
    while read; do
        "${@:-echo}" "$REPLY";
    done
}
bajl:md2js () 
{ 
    local -A jq=('header' '[{ m4: { ME: "\($ns)" }}, { id, ns: "ME" }] + input' 'md2js' 'def txt: .c[2] | map(.c // " ") | join("");
def f($b):
  if $b.t == "Header" then ($b | txt) as $h |
    if $h | startswith("id ") then . + [{id: $h[3:]}] else . + [null] end
  elif $b.t == "CodeBlock" and .[-1] then
    .[-1][$b.c[0][1][0] // "txt"] = $b.c[1]
  end;
.blocks | reduce .[] as $b ([]; f($b)) | map(values)');
    pandoc -t json | jq "${jq[md2js]}" | jq "${jq[header]}" -n --arg ns ${1:?}
}
bajl:ns () 
{ 
    (($# == 0)) || bajl:fail too many args;
    compgen -c ns: | cut -d: -f2
}
bajl:nsp () 
{ 
    compgen -c ns:${1:?} > /dev/null
}
bajl:nss () 
{ 
    bajl:loop bajl:nss1 "$@"
}
bajl:nss1 () 
{ 
    local jq='.[].ns // empty';
    yq -oj < ${1:?} | bajl:self -r
}
bajl:optal () 
{ 
    echo shopt -s expand_aliases
}
bajl:opts () 
{ 
    local opt val tmp i;
    args=();
    until [[ $# -eq 0 ]]; do
        case "$1" in 
            --)
                shift;
                break
            ;;
            --*=*)
                opt="${1%%=*}";
                val="${1#*=}";
                opts["${opt:2}"]="$val";
                shift
            ;;
            --*)
                opts["${1:2}"]="1";
                shift
            ;;
            -[0-9]*)
                args+=("$1");
                shift
            ;;
            -)
                args+=("$1");
                shift
            ;;
            -*)
                tmp=${1:1};
                for ((i = 0; i < ${#tmp}; i++ ))
                do
                    opt="${tmp:$i:1}";
                    opts[$opt]=$((opts[$opt] + 1));
                done;
                shift
            ;;
            *)
                args+=("$1");
                shift
            ;;
        esac;
    done;
    cont=("$@")
}
bajl:prudent () 
{ 
    echo set -euo pipefail;
    echo shopt -s inherit_errexit
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
bajl:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA5VXbW/TSBD+fr9iLjU0buu06aGTzm6OFlQOJEAcFR9OjoUce00cnHVqb0pLmv9+
z+zaTkyTEqyq2Z2d95239RcdWXbcziicZJ2jThpjnc9UiXU5xnqPPpWCsjwKM3IuiI+8ahsWX0qK
cqk8DaZhxzofdiiVhNNMFENp8HBIN/hV0xmlniYbdO2hnEuVZuT7ZO2RI67phILAozgfSsIXhZAL
ln3N0sD4cxybynGaQOqoEOFXz1s/Oxgc2CxwAMpF/8mTwcFy2PFYvIHsHQw0gBX2GYKFewpQwOdA
40PDvs3XXpH0G4L+Zmz/xPkrAAVbejjoGiPsTZi74IARPDdguf3lCs5fkhfU7aY0oBOPUjoja7EH
3CU2h4dk2ytvrn+1e4DpWikz7WxEKn0L/4OB1e2udnRIfdtu48e5FG3IAyt+5g1RhtFQMiNPh5TG
QzTZiEOlEIe/EIFD2VkebQjraXw64bieXHfcRWcswlgUAPsLmj5zaUHvLl1wGA67lixtRN1yeQRo
Gh+RLPnk3SUD2QOpnM0VOBmObicWCalb5VIv8k8DuqdpOOv2Ijo+Bhn+bIAmeSphFJsOQ0GQdK2R
7bL5aULWqKdoMADua60XyNRYSAIOaMEb/ivJGtO98ReTYEOlCgtVfkvVGLzTWMvShD2o6S/S2AWe
/4cbQG+RIaM0XM6zDHsZMzORteS/zGPxAu79ChVCGVPPd/qB5mkk670P/Mg/CXwsTwJjJ5REViAW
9Vk/0LxlDGt7I+ZXQt1CxPMISviBNmdEXR8prz1hV25DDs5FaeMKTQGaQYk8IkfRpMwlO/Ka73kx
ufa1+wOEbwtqLlaDHYnURZDgAonz5/lyc2QkYZrVBW8uS6HIuSEGeuRqtrx2n1uLV5/ev3x/8e4S
5i3JOocMzTAFQx9cOsHRQ+ZZns9q5iZsUQQ5c1Mulcz9XBcUTlay+gxJzU6KzepmaalWHPMZiWic
V8H/c304aWpqODxJMwHveigkqB7vLj68evP20j+HfX/TCW7l6dNKR4elLHU8W4s1vF1kQk4t8tuY
BaJyx9rgh7w/Xn54+9/jDihFltT8zMVPrg1x7YEHJGrlsrNHYwFh3PItCOvOBlcY0K3qP3S33Gw6
I9cMTWh6VGuAJJhwWoymz/A/xrXiR0xTtVk1WZYt1bDfXQ9GropfB/nXQ0ogbcV0pu5+dAzdXZOT
T7i8wNHkFNvDEIt1jQxod6Uq/JpHlE9nX1C8nKjSxOVu0MBQhh+7uTRuuwf73TVh5HX3rAwTPLtU
jimLqKk1OuS2+SaRLVUSubsmwG1oK3dW0u9Nw4tFlIUFkjbZJrvxA6yqg7ch3kLFB+sqY7+7zoxc
U2OgQ/V8cXH1+vPF2zcXV5dXvtE/wHxH9/e6sHKhk7lCh6EwS9ELkFsru2Bwmx7ldltK1GJRvva4
g3HNqoWoPEdPkXfa9B9DCR6J5qj0aJFOcrqN/WxDbDZxiBJ5HIubY+6nmxlo40Q7LitY/9F6VSPV
MWldfPznqjfLy1SluURE3pPf811LBkdop5Z02bekihAq56XwA5O9IlLdLNR1RYlSdZv5xsWkwC03
SYtVZQRtE2uVC/UlwWKvqgWyWGupfbPWjVny8Nm6Ne4h+lzH4OL3Hw+rVvIQvCWs8+KLaNdmA/qF
1DL4NY8enXVXPf3JE/dg6W5OOd1gq8kg8Uj7qc8xu6hvk/dtZH3gtXZA8mhpbymnedjUHKMoWV1U
7co6TMyb9EV7qRF+bv+3sGjqkpkZhnuEoBZFqERMoztqjzhHFN7kmCpFXLWkR7ljBA+zFvtyzG8/
By655THuc50NG+2fFfNYSNVmwA4X85xm6UyYgazNOJVjUaTqsygKcbuLktDkh/K66aqBlRdqa4XF
cXv+AtNf6Hmj/k4JtwqZatVdxVoVDd+5Ieldgvzrb+vTo1qeviKPql49qpX2uNrrBPfYlkcLE781
nDWWXHdXJVc/xFjE+uOeqzIjIEWwdJzqnW80YPuq97x5/jHNCpGTrD5udKxk6vxLBg+bhetY/WXD
Vt+olZhR8/xfPWpvaSdhuW4ap4vHWj5eqUsnmjaZazg0ftWy9/UIYUD7m5ncTbNT0DdBFdZh6Zkp
b1VdjLhtb1wOiLplrGo9R0nXhrPOzs5oH9CevU8jhNKfz9D/wPl7FCo92MAzsLNSo5rBmqHH4d8v
39MZj6yGuh4R11tC+bFg9YLf/geeUlEMXBIAAA==
' | zcat | jq
}
bajl:tst () 
{ 
    < ${1:?}
}
bajl:txt () 
{ 
    bajl:loop bajl:tst "$@" && bajl:loop bajl:txt1 "$@"
}
bajl:txt1 () 
{ 
    baj:header;
    baj:asjs < ${1:?} | baj:bm4 | baj:dist | baj:emit
}
bajl:warn () 
{ 
    echo \# generated by ${FUNCNAME[1]}, avoid edit
}
bajl:with-lib () 
{ 
    (($#)) || bajl:fail;
    bajl:optal;
    until [[ $# == 0 || $1 == -- ]]; do
        bajl:lib1 $1;
        shift;
    done;
    [[ $1 == -- ]] && shift;
    bajl:def self;
    (($#)) && { 
        f=${BASH_ALIASES[$1]:-$1};
        shift;
        echo $f "${@@Q}"
    }
}
bajl:yml2sh () 
{ 
    bajl:load ${1:?};
    bajl:nss1 $1 | bajl:args bajl:as-cmd
}
bajl:zsrc () 
{ 
    local jq='"\($ns):src () { <<< '\''\(.)'\'' base64 -d | zcat | jq; }"';
    ${1:?}:src | jq -c | gzip | base64 | bajl:self --arg ns $1 -sRr
}
ns:bajl () 
{ 
    bajl:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f baj:asjs baj:bm4 baj:clean baj:dist baj:emit baj:header baj:init baj:main baj:mk-alias baj:src ns:baj ns:bajl
export -f bajl:aliases bajl:aliases1 bajl:args bajl:as-cmd bajl:as-lib bajl:def bajl:def1 bajl:exp bajl:exp1 bajl:fail bajl:fn bajl:fn1 bajl:fns bajl:forget bajl:forget1 bajl:ids bajl:ids1 bajl:lib bajl:lib1 bajl:list bajl:listid bajl:listid1 bajl:load bajl:loop bajl:map bajl:md2js bajl:ns bajl:nsp bajl:nss bajl:nss1 bajl:optal bajl:opts bajl:prudent bajl:self bajl:src bajl:tst bajl:txt bajl:txt1 bajl:warn bajl:with-lib bajl:yml2sh bajl:zsrc ns:bajl
eval "$@"
