# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias git2md='ns:git2md'
alias check-tty='git2md:check-tty'
alias relative-file-to-js='git2md:relative-file-to-js'
alias git-file-to-url='git2md:git-file-to-url'
alias git-repo-to-md='git2md:git-repo-to-md'
alias git-site='git2md:git-site'
alias git-repo-to-js='git2md:git-repo-to-js'
alias git-url='git2md:git-url'
alias relative-file-to-md='git2md:relative-file-to-md'
alias git-repo-to-url='git2md:git-repo-to-url'
alias git-commit-to-js='git2md:git-commit-to-js'
alias git-branch-or-tag='git2md:git-branch-or-tag'
alias gr2md='git2md:gr2md'
alias git-url-to-md='git2md:git-url-to-md'
alias git-repo='git2md:git-repo'
alias git-commit-to-md='git2md:git-commit-to-md'
alias git-repo-and-commit-to-js='git2md:git-repo-and-commit-to-js'
alias git-file-to-md='git2md:git-file-to-md'
alias gc2md='git2md:gc2md'
alias gf2md='git2md:gf2md'
git2md:check-tty () 
{ 
    [ -t 0 ] && bajl:fail "input shouldn't be a TTY"
}
git2md:gc2md () 
{ 
    git2md:git-commit-to-md "$@"
}
git2md:gf2md () 
{ 
    git2md:git-file-to-md "$@"
}
git2md:git-branch-or-tag () 
{ 
    if [ "$1" ]; then
        git tag | grep $1 || bajl:fail no $1 tag;
    else
        git branch --show-current;
    fi
}
git2md:git-commit-to-js () 
{ 
    pretty='{ _XXX_comment_XXX_: _XXX_%s_XXX_, _XXX_commit_XXX_: _XXX_%H_XXX_ }';
    git log -${1:-1} --pretty="$pretty" | sed -e 's/"/\\"/g' -e 's/_XXX_/"/g'
}
git2md:git-commit-to-md () 
{ 
    local -a lv=('id');
    local jq='"\n    " as $s | "[\(.comment)]:\($s)\(.url)/commit/\(.commit)\($s)\"github.com commit\"\n"';
    git2md:git-repo-and-commit-to-js "$@" | bajl:self -r;
    alias gc2md=$id
}
git2md:git-file-to-md () 
{ 
    git2md:check-tty;
    git2md:git-file-to-url "$@" | git2md:git-url-to-md
}
git2md:git-file-to-url () 
{ 
    xargs -ri echo https://$(git-site)/$(git-repo)/blob/$(git-branch-or-tag "$@")/{}
}
git2md:git-repo () 
{ 
    local jq='split(":")[1]';
    git2md:git-url | bajl:self -Rr
}
git2md:git-repo-and-commit-to-js () 
{ 
    local jq='input as $r | [inputs] | map([$r, .] | add)[]';
    { 
        git2md:git-repo-to-js;
        git2md:git-commit-to-js "$@"
    } | bajl:self -n
}
git2md:git-repo-to-js () 
{ 
    local jq='{ url: .}';
    git2md:git-repo-to-url | bajl:self -R
}
git2md:git-repo-to-md () 
{ 
    git2md:git-repo-to-url | git2md:git-url-to-md repo
}
git2md:git-repo-to-url () 
{ 
    local jq='[inputs] | "https://\(first)/\(last)"';
    { 
        git2md:git-site;
        git2md:git-repo
    } | bajl:self -nRr
}
git2md:git-site () 
{ 
    local jq='split(":")[0]|split("@")[1]';
    git2md:git-url | bajl:self -Rr
}
git2md:git-url () 
{ 
    git config --get remote.origin.url
}
git2md:git-url-to-md () 
{ 
    local jq='"\n    " as $s
| (if $what == "repo" then split("/")[-1] else split("/")[7:] | join("/") end) as $p
| "[\($p)]:\($s)\(.)\($s)\"github.com \($what)\"\n"';
    bajl:self -Rr --arg what ${1:-file}
}
git2md:gr2md () 
{ 
    git2md:git-repo-to-md "$@"
}
git2md:relative-file-to-js () 
{ 
    local jq='{ url: ., name: . }';
    bajl:self -R
}
git2md:relative-file-to-md () 
{ 
    local jq='"\n    " as $s | "[\(.name)]:\($s)\(.url)\($s)\"github.com relative file\"\n"';
    git2md:check-tty;
    git2md:relative-file-to-js | bajl:self -r
}
git2md:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA6VVTY+bMBC991eMLLoJUgibvVQiitRjz9UetgJUETDgLTHUdnZbJfnvHRscyAfZ
SM0htsfOm5k3bybhjnBJAlIw9bTJyIywrD15W1HhUZbtEdKa56wAzyuoAkE3taLzWrCC8bl+eZiN
Agna1Hh+/Y1n2VRMTSMSRMQNF/HAgfYHe5C0ysH7Lm4BSqboVcDHeG/PX//HgY7YU3VHgfETMt5s
lYwRISKlUo0MfD+KpjkTUrl6VyW4iYj1uAMb6hIs5hIOxwj4fSEY6zGFQWAI1CXVPgND8xiieLoO
hL+LiINk3Yrl6MOSEZEo4oCfiEAiwZER38OU5eC8l4mC1QovtAe8ViXlYIvi66J4ixhoJemp9Uug
qX2tGe8sQHnmGvRGo0ckRI6dxo0DvUoXv+eu3UY6znK7nqf1BrRRx2HsGGhfE1t7VHEiCjDBOrtF
4OWsoocxCtKSpr88pf5amBA8BY8Qw8MD5AmrMDijDpBlva0yPlGwppDA8/OP28SuRcLT0quFp5LC
oiONoS7KAtmLly2BugHxia458grOAvb71jWv9Qnvli2p+mULi0liPO9euhWCcrWEnN2KRVPQa95E
8gdJkuAJBjQta7Cqd6ZW2W6317V2/XVVrzvDSWKdwlx/N0rxMIBeqEfi2w4aRNhBnvfAKHx+Jv/e
1x3yt73yKq3+d4AuA5gfxnuzk9otXNTqBheLbIAaQTHf1WQHP19eXn7qJ1g7sw9a02dplln/gJ3e
fzMLHCYR12KoahzaRuSLA0qic4BZtztDoqQZeBQm0te9pz/ELyadycD5xvIhSwnPztMyhLXtoZtZ
oLvBLN0kzTR0xAzm+pRkmRvGpxO0Z79VwRC+K97JWL2PcWOv3kgQ6tt4bK6BHTzzrhIn4wcr7fot
pm/fMHV9KLV3FxNplLle4W1eYglJxTCoIsWkVg4bF3t6JvZh1h/IXdAqUeyNHhvkUvMz4MmG4gYO
Z2P1btAbfyQ94drLBdtXqbX4oPEvGB4MkSvZ9fySQ/zpH6edZzoNCQAA
' | zcat | jq
}
ns:git2md () 
{ 
    git2md:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f git2md:check-tty git2md:gc2md git2md:gf2md git2md:git-branch-or-tag git2md:git-commit-to-js git2md:git-commit-to-md git2md:git-file-to-md git2md:git-file-to-url git2md:git-repo git2md:git-repo-and-commit-to-js git2md:git-repo-to-js git2md:git-repo-to-md git2md:git-repo-to-url git2md:git-site git2md:git-url git2md:git-url-to-md git2md:gr2md git2md:relative-file-to-js git2md:relative-file-to-md git2md:src ns:git2md
eval "$@"
