# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias jqsh-ansible='ns:jqsh-ansible'
alias fn-ansible='jqsh-ansible:fn-ansible'
alias convert-json-out='jqsh-ansible:convert-json-out'
alias txt-out-to-md='jqsh-ansible:txt-out-to-md'
jqsh-ansible:convert-json-out () 
{ 
    local jq='map({ node } + { out: (.stdout_lines | add | fromjson) })';
    bajl:self "$@"
}
jqsh-ansible:fn-ansible () 
{ 
    local jq='.. | .results? // empty | map({ node } + (.ansible_facts.command | { rc, stdout_lines }))';
    local js='[{"hosts":"all","gather_facts":false,"vars":{"rol":{"delegate_to":"localhost","run_once":true}},"tasks":[{"set_fact":{"stdin":"{{ lookup(file, stdin) }}"},"vars":{"file":"file","stdin":"/dev/stdin"},"delegate_to":"localhost","run_once":true},{"command":{"argv":["bash"]},"args":{"chdir":"{{ dir | default(omit) }}","stdin":"{{ stdin }}"},"failed_when":false,"register":"command"},{"delegate_to":"localhost","run_once":true,"set_fact":{"command":"{{ hostvars[node].command }}"},"loop":"{{ ansible_play_hosts_all }}","loop_control":{"loop_var":"node"}}]}]';
    ANSIBLE_STDOUT_CALLBACK=json ansible-playbook <(echo "$js") "$@" | bajl:self
}
jqsh-ansible:src () 
{ 
    jq <<< '[{"ns":"jqsh-ansible","id":"convert-json-out","jq":"map({ node } + { out: (.stdout_lines | add | fromjson) })"},{"ns":"jqsh-ansible","id":"txt-out-to-md","jq":".[] | \"# \\(.node)\", \"\", \"```\", .stdout_lines[], \"```\", \"\"","sh":"self -r"},{"ns":"jqsh-ansible","id":"fn-ansible","jq":".. | .results? // empty | map({ node } + (.ansible_facts.command | { rc, stdout_lines }))","sh":"ANSIBLE_STDOUT_CALLBACK=json ansible-playbook <(echo \"$js\") \"$@\" | self","tt":"<<< id fn-ansible -bl mapa2,bastion1\n# as root, even if ssh node -l root fail (provided `become` works)\nwith-lib a-lib -- a-func | fn-ansible -bl a-node -CD","js":[{"hosts":"all","gather_facts":false,"vars":{"rol":{"delegate_to":"localhost","run_once":true}},"tasks":[{"set_fact":{"stdin":"{{ lookup(file, stdin) }}"},"vars":{"file":"file","stdin":"/dev/stdin"},"delegate_to":"localhost","run_once":true},{"command":{"argv":["bash"]},"args":{"chdir":"{{ dir | default(omit) }}","stdin":"{{ stdin }}"},"failed_when":false,"register":"command"},{"delegate_to":"localhost","run_once":true,"set_fact":{"command":"{{ hostvars[node].command }}"},"loop":"{{ ansible_play_hosts_all }}","loop_control":{"loop_var":"node"}}]}]}]'
}
jqsh-ansible:txt-out-to-md () 
{ 
    local jq='.[] | "# \(.node)", "", "```", .stdout_lines[], "```", ""';
    bajl:self -r
}
ns:jqsh-ansible () 
{ 
    jqsh-ansible:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f jqsh-ansible:convert-json-out jqsh-ansible:fn-ansible jqsh-ansible:src jqsh-ansible:txt-out-to-md ns:jqsh-ansible
eval "$@"
