# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias llmfs='ns:llmfs'
alias files='llmfs:files'
alias enc='llmfs:enc'
alias b64='llmfs:b64'
alias content='llmfs:content'
alias indir='llmfs:indir'
alias conf='llmfs:conf'
alias core='llmfs:core'
alias dec='llmfs:dec'
alias merge='llmfs:merge'
llmfs:b64 () 
{ 
    sed /${1:-^}/s/text/b64/
}
llmfs:conf () 
{ 
    local jq='{ $mode, file: . }';
    bajl:self -c --arg mode ${1:-text}
}
llmfs:content () 
{ 
    local js='{"text":"cat","b64":"base64"}';
    local jq='"< \(.file) \($map[.mode]) | jq -nR [inputs]"';
    while read; do
        echo $REPLY;
        bajl:self -r --argjson map "$js" <<< $REPLY | dash;
    done
}
llmfs:core () 
{ 
    local jq='{ llmfs: "core", files: . }';
    bajl:self -s "$@"
}
llmfs:dec () 
{ 
    local js='{"text":"cat","b64":"base64 -d"}';
    local jq='.files[] | ["<<-\"!\" \($map[.mode]) | install --backup=t /dev/stdin \(.file | @sh)"] + (.lines | map("\t" + .)) + ["!"] | .[]';
    bajl:self -r --argjson map "$js"
}
llmfs:enc () 
{ 
    llmfs:content | llmfs:merge | llmfs:core "$@"
}
llmfs:files () 
{ 
    [[ "$1" == -z ]] && jq -sR '(./"\u0000")[:-1][]' || jq -R
}
llmfs:indir () 
{ 
    local jq='.files[].file |= "\($dir)/\(.)"
';
    bajl:self --arg dir ${1:?}
}
llmfs:merge () 
{ 
    local jq='try repeat([input, input]) | first + { lines: last }
';
    bajl:self -n
}
llmfs:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA4VSTW+cMBC991dMLZSAskBXqnogrJpLbz1Ue6tsIjnYBLasIdjbr13+e2fMkijV
0nLAM/Z8vJn3+JEZyzLWtvvKshVrFDpV02pybI0O5yBYsBYMNhuIf0NRwNUV7J4gtlu4DpNUMCEO
7/ATLOJZvC54cQ2nkw/ZCsPG1aUeZWcqtHdPaB8h2HdKr4AaZ5DAODe3uq0gLiGO5fAIFATBcZ3F
Tv9042Lthw/vXwooSH3K/ZjalPJSfE6XUTltHAHDtyOjeLqWdEVlsbi0Go3xjF2wHIQIE4IekRXs
Zc8TglpEMG3BbIE3pj84Wwg2I/tRYwYMWqpbUB3osu4g2H768vnrLeR5frZh2sAwbWBnOwNYnxjZ
WaTkBEramgoYvbiOvR4e9bxrN/zCpr2WLpwwrcAfHmzVDNbBDRyhbYy2GbQSfVr0Kz6WOR30C6f+
KUOodC3YxK69QK+lce5wM5eralPO8Wd6EKmfCU+q/e/0xqhmmFF5miwv/AmnDZB4wwAjopRYjND/
a1ivPAzwwvs4LnRRuvy/aCBWz7qZkeAMHDWUx0II9pZ+F0TUGOtk2yKYB1l+O/QbB6nS31PrVGOe
5YeBd7bGEQqkMEw8hbQq2Yc0psPSN5BEEf459WLUPOHF63kXpMbG4s0fKFNlxi0EAAA=
' | zcat | jq
}
ns:llmfs () 
{ 
    llmfs:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f llmfs:b64 llmfs:conf llmfs:content llmfs:core llmfs:dec llmfs:enc llmfs:files llmfs:indir llmfs:merge llmfs:src ns:llmfs
eval "$@"
