# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias llmfs='ns:llmfs'
alias enc='llmfs:enc'
alias dec='llmfs:dec'
alias mini='llmfs:mini'
llmfs:dec () 
{ 
    local jq='.files[] | ["<<-\"!\" > \(.file | @sh) cat"] + (.lines | map("\t" + .)) + ["!"] | .[]';
    bajl:self -r
}
llmfs:enc () 
{ 
    local jq='{ file: input, lines: [ inputs ] }';
    while read; do
        { 
            jq -R <<< "$REPLY";
            jq -R < "$REPLY"
        } | bajl:self -n;
    done | llmfs:mini "$@"
}
llmfs:mini () 
{ 
    local jq='{ llmfs: "mini", files: . }';
    bajl:self -s "$@"
}
llmfs:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA31Qu27DMAzc+xVXooON2voARyiyZOtQZCtEDUYswwoUNYlSdHD976UUoEGBoAtB
3h2PDzNTTNRRCIcxUUN+kOLgo5d8f5J8RqE6cIGZGow+OAEUFhGlSUTJhRFtEs3TmomW5p6ri7ub
afbo4OPx89Ig+JgNzbVOsDfnr0mEOLt+WGH4wAytdR6z3by9vjNhf0K7XeEetuAb18Vi7o1O6nzC
/1sO7ndLVQ41VvoMk9YtM9NjDngBc1V4IddpqrHrL0wWz6hUOScP648VE7MQgqu6lmiyA2VLZezf
951psQ8/gJbRm5ABAAA=
' | zcat | jq
}
ns:llmfs () 
{ 
    llmfs:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f llmfs:dec llmfs:enc llmfs:mini llmfs:src ns:llmfs
eval "$@"
