# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias llmfs='ns:llmfs'
alias files='llmfs:files'
alias enc='llmfs:enc'
alias b64='llmfs:b64'
alias content='llmfs:content'
alias indir='llmfs:indir'
alias conf='llmfs:conf'
alias core='llmfs:core'
alias dec='llmfs:dec'
alias merge='llmfs:merge'
llmfs:b64 () 
{ 
    sed /${1:-^}/s/text/b64/
}
llmfs:conf () 
{ 
    local jq='{ $mode, file: . }';
    bajl:self -c --arg mode ${1:-text}
}
llmfs:content () 
{ 
    local js='{"text":"cat","b64":"base64"}';
    local jq='"< \(.file) \($map[.mode]) | jq -nR [inputs]"';
    while read; do
        echo $REPLY;
        bajl:self -r --argjson map "$js" <<< $REPLY | dash;
    done
}
llmfs:core () 
{ 
    local jq='{ llmfs: "core", files: . }';
    bajl:self -s "$@"
}
llmfs:dec () 
{ 
    local js='{"text":"cat","b64":"base64 -d"}';
    local jq='.files[] | ["<<-\"!\" \($map[.mode]) | install --backup=t /dev/stdin \(.file | @sh)"] + (.lines | map("\t" + .)) + ["!"] | .[]';
    bajl:self -r --argjson map "$js"
}
llmfs:enc () 
{ 
    llmfs:content | llmfs:merge | llmfs:core "$@"
}
llmfs:files () 
{ 
    [[ "$1" == -z ]] && jq -sR '(./"\u0000")[:-1][]' || jq -R
}
llmfs:indir () 
{ 
    local jq='.files[].file |= "\($dir)/\(.)"
';
    bajl:self --arg dir ${1:?}
}
llmfs:merge () 
{ 
    local jq='try repeat([input, input]) | first + { lines: last }
';
    bajl:self -n
}
llmfs:src () 
{ 
    jq <<< '[{"ns":"llmfs","id":"files","sh":"[[ \"$1\" == -z ]] && jq -sR '\''(./\"\\u0000\")[:-1][]'\'' || jq -R\n"},{"ns":"llmfs","id":"conf","jq":"{ $mode, file: . }","sh":"self -c --arg mode ${1:-text}\n"},{"ns":"llmfs","id":"b64","sh":"sed /${1:-^}/s/text/b64/"},{"ns":"llmfs","id":"content","js":{"text":"cat","b64":"base64"},"jq":"\"< \\(.file) \\($map[.mode]) | jq -nR [inputs]\"","sh":"while read; do echo $REPLY; <<< $REPLY self -r --argjson map \"$js\" | dash; done\n"},{"ns":"llmfs","id":"merge","jq":"try repeat([input, input]) | first + { lines: last }\n","sh":"self -n"},{"ns":"llmfs","id":"core","jq":"{ llmfs: \"core\", files: . }","sh":"self -s \"$@\""},{"ns":"llmfs","id":"enc","sh":"content | merge | core \"$@\""},{"ns":"llmfs","id":"indir","jq":".files[].file |= \"\\($dir)/\\(.)\"\n","sh":"self --arg dir ${1:?}"},{"ns":"llmfs","id":"dec","js":{"text":"cat","b64":"base64 -d"},"jq":".files[] | [\"<<-\\\"!\\\" \\($map[.mode]) | install --backup=t /dev/stdin \\(.file | @sh)\"] + (.lines | map(\"\\t\" + .)) + [\"!\"] | .[]","sh":"self -r --argjson map \"$js\""}]'
}
ns:llmfs () 
{ 
    llmfs:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f llmfs:b64 llmfs:conf llmfs:content llmfs:core llmfs:dec llmfs:enc llmfs:files llmfs:indir llmfs:merge llmfs:src ns:llmfs
eval "$@"
