# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias llmfs='ns:llmfs'
alias enc='llmfs:enc'
alias dec='llmfs:dec'
alias mini='llmfs:mini'
llmfs:dec () 
{ 
    local jq='.files[] | ["<<-\"!\" > \(.file | @sh) cat"] + (.lines | map("\t" + .)) + ["!"] | .[]';
    bajl:self -r
}
llmfs:enc () 
{ 
    local jq='{ file: input, lines: [ inputs ] }';
    while read; do
        { 
            jq -R <<< "$REPLY";
            jq -R < "$REPLY"
        } | bajl:self -n;
    done | llmfs:mini "$@"
}
llmfs:mini () 
{ 
    local jq='{ llmfs: "mini", files: . }';
    bajl:self -s "$@"
}
llmfs:src () 
{ 
    jq <<< '[{"ns":"llmfs","id":"mini","jq":"{ llmfs: \"mini\", files: . }","sh":"self -s \"$@\""},{"ns":"llmfs","id":"enc","jq":"{ file: input, lines: [ inputs ] }","sh":"while read; do { <<< \"$REPLY\" jq -R; < \"$REPLY\" jq -R; } | self -n; done | mini \"$@\""},{"ns":"llmfs","id":"dec","jq":".files[] | [\"<<-\\\"!\\\" > \\(.file | @sh) cat\"] + (.lines | map(\"\\t\" + .)) + [\"!\"] | .[]","sh":"self -r"}]'
}
ns:llmfs () 
{ 
    llmfs:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f llmfs:dec llmfs:enc llmfs:mini llmfs:src ns:llmfs
eval "$@"
