# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias umdq='ns:umdq'
alias md2yml-v1='umdq:md2yml-v1'
alias md2yml='umdq:md2yml'
umdq:install () 
{ 
    cargo install --git https://github.com/yshavit/mdq
}
umdq:md2yml () 
{ 
    local js='{"bash":"sh","json":"js","txt":"tt","sh":"tt"}';
    local jq='def item:
  .section as { $title, $body }
  | $body | map(.code_block // empty | { (.language | $map[.] // .): (.code / "\n") }) | add as $keys
  |  ($title / " ") | { type: .[0], id: .[1] } + { $keys };
def print:
  def id:
    def each:
      def yml: .value | map("  " + .);
      def others:[ "  \(.key): |-" ] + (.value | map("    " + .));
      if .key == "yml" then yml else others end;
      [ "- id: \(.id)" ] + (.keys | to_entries | map(each) | add);
  if .type == "raw" then .keys.yml else id end  | join("\n");
.items | map(item) | map(print) | join("\n\n")';
    mdq -o json '# /^(raw|id)/' | jq "$jq" -r --argjson map "$js"
}
umdq:md2yml-v1 () 
{ 
    local js='{"bash":"sh","json":"js","txt":"tt","sh":"tt"}';
    local jq='def item:
  .section | (.title / " ")[-1] as $id
  | .body | map(.code_block // empty | { (.language): .code }) | add as $keys
  | { $id } + $keys;
def filter: .items | map(item);
def head: first | if .id | test("^head") then .json | fromjson else [.] end;
def norm: with_entries(.key |= ($map[.] // .));
filter | head + .[1:] | map(norm)';
    mdq -o json '# /^(head|id)/' | jq "$jq" --argjson map "$js" | yq -P
}
umdq:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA61T247aMBB971eMXKRNVJJ0+5h2/6HvSXZlsCFmEwdiwxZB/r1nnMB2tWylSpVQ
GHtmzpnLcXES1olc7Fu1E3NhFGxjnZdNw0e4CmGlqObC1XAtZb/uaAqgJFkbT7X3W5dnGex6v0iX
XZsdXS0PxmcMOsxvULTq27FtksM9LjZwnsRCBgJ8+KazsOGYC//Lw/ReTBXAGhCxg6n0iozXbV5a
otTppTedpTNFqTe+0ZRRKfCLi+S+IuloZhRHnilddOqI/1ZuI9Sr9NOi6ZbPlGWk261n1wkojbTr
vVzrOKcQRUMMj1QqgD3roxvhToxMA30ZL7+XlitbmcbrHqlcopvY2I6ngFpLlSOsdx5es0KkguG1
81EpHtmN4snX2lLKI4Fz1XdtMHXjNBVpRdqqCc92fZvTC7bwpK3vjXZRinro/EDRDOQcjQ7TmAsY
qwMi06DytLjPq6lIBoov88bSKOkokN59puwx4oyzUXF2h/jNDhOebXaYdJJAHCEOIOHW4fZMRwD8
LC3vklf5g5zbpq2iVw38RSL/Xx/YHRYWFDKnWVDCMO5x9m+y4Iw/x5rTmBV0V5aWl/eBYrCQtxIN
0P641dBL8bWak1FsQbcsq9OYS8O06W1vrA9dhRZVMMeDlst6Oo4XmCGQDrLZ66k1MDIrds5CeI3s
oLTe5QWFgDKIB02dE5wrhEfvUK44r0AsYxbdwwN84EZAEDDMUbMjyyTbMYcZk9Axs0JZV8LQNZ5E
d1H0RM5dTpMdqZmWxzfy9vLlwhsg0is7XhiYeQWbztjosidgvH+mkx2GHb/NCEkfvxDw33wg/e03
8uHbEEP16TcBttYtoQUAAA==
' | zcat | jq
}
ns:umdq () 
{ 
    umdq:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f umdq:install umdq:md2yml umdq:md2yml-v1 umdq:src ns:umdq
eval "$@"
