# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias misc='ns:misc'
alias utree='misc:utree'
alias md-auto-wrap='misc:md-auto-wrap'
alias list-renamed-claude-sessions='misc:list-renamed-claude-sessions'
alias re-date-ln='misc:re-date-ln'
alias tiktoken='misc:tiktoken'
misc:list-renamed-claude-sessions () 
{ 
    local jq='select(.display | test("^/rename"))
';
    bajl:self < ~/.claude/history.jsonl
}
misc:md-auto-wrap () 
{ 
    pandoc -f gfm -t gfm --wrap=auto --columns=${1:-80}
}
misc:re-date-ln () 
{ 
    local perl='BEGIN { $j = JSON::PP->new->ascii }
chomp; print $j->encode([ $_, scalar readlink($_) ]), "\n"';
    local jq='map(@sh) | "touch -hr \(last) \(first)"';
    find -maxdepth 1 -type l -print0 | perl -MJSON::PP -0ne "$perl" | bajl:self -r
}
misc:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA51UUW/TMBB+51ecQiUcUXfdG+rohEAIgcSYxOMyKi+5Lm4dO9jOtmobQvyGPfLr
+CWcnWZJ0YYQVaTenT/ffff57JPrRLtkllTS5ck4kUWwCy4ab/ilFTXFXEmxWujC5MCXcL6sgPv2
L0LmAUx2blRTaTcfXe/P+IvpbaaT2/ED6ZV0nlvUosKC50o0BXKHzklD0HGy+koYhwpzzyaFdLUS
G7gBj86zLPmy1+7MkjSlAlt2L+Hb3qRNtVdSemM3k5UzWgElWj5GxCIvhEeuQp4araLY67fv3h/B
NYxWMIcPnz8dzWbHx/xQ4yU/FC6XEqivvDRVfQC1ldoTkh+izk2B7ARGizG4XChhwaIolNRrNlqk
cJqOIUuyTGdJ12IlavbKlSn1liXeNHkJvLSQZUwJ59NgLKUlK26JbS6lLoBX4qrA2pewT+ewqREU
8EhlSqlCG8A/dsyBTzVS/lGIZwkBgiDA7WOaeLn2Zo1RkQ35sqqN9eA2bgzd2gFQvyRP50/O0S+i
BFKfs2e52p9O14sz4fBZulWJKdSMIJOtUpRv4jzhJ0EmlqbD02wuwDY6TJekLrsqUG98aSicx342
JOcjPTTeInYyF7iE4LMRiYfap7NMA0gKBunmc0pmzlY0bKSOL1GHVYAJCAcjWoCbNsBaB9a4cWlc
FEotgtcj+ghQu+e+bIFkdxgqG10qOx1UgzAbSWujcthFhxm9IYm9lRicMDsdiMgSJFaSxVVXKcYv
hGowrqyHcRaBxIFFMhz205apdIswewvpsdrdQM2fjNanLYzShtV+/Sm8KY1xCLnRmqQ0FsLpF0DH
VRsnPV3tQbagwk6poARJ8Ovu7tfdd/rIjjrE2M9BTBctg77Owzzaow50vNSNCPX/i1F7ND2XH1u/
46Hxija0xf5g8n4J7VyN6SXIG+vwIBy/QrEEphulgNgbqmPpaVg1ju5YaS5B+gGt3mxHJwr/98Ht
fuGxuR/5YN5LFr11uhcfI3i+u411NQY3Bp7vNBpuar9hOK7/WDkW3smhi969zx4expWRmoW7sY1u
kX3R7t7QwkGmI+sI756S7WuX3J4++Q2p9YVN6gYAAA==
' | zcat | jq
}
misc:tiktoken () 
{ 
    local py='import sys, tiktoken; enc = tiktoken.get_encoding('\''cl100k_base'\''); print(len(enc.encode(sys.stdin.read())))
';
    uv run --with tiktoken python -c "$py"
}
misc:utree () 
{ 
    local jq='def tree($indent):
  if type == "object" then
    . as $obj |
    ($obj | keys) as $all_keys |
    ($all_keys | length) as $len |
    if $len == 0 then
      ""
    else
      $all_keys | to_entries | map(
        .key as $idx |
        .value as $k |
        ($idx == ($len - 1)) as $is_last_item |
        ($obj[$k]) as $val |

        # Choose connector based on position
        (if $is_last_item then "└── " else "├── " end) as $connector |

        # Choose indent continuation based on position
        (if $is_last_item then "    " else "│   " end) as $next_indent |

        # If object, recurse; if leaf (null or other), just show it
        (
          if $val | type == "object" then
            "\($indent)\($connector)\($k)/\n" +
            ($val | tree($indent + $next_indent))
          else
            "\($indent)\($connector)\($k)\n"
          end
        )
      ) | join("")
    end
  else
    ""
  end;
tree("")';
    bajl:self -r
}
ns:misc () 
{ 
    misc:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f misc:list-renamed-claude-sessions misc:md-auto-wrap misc:re-date-ln misc:src misc:tiktoken misc:utree ns:misc
eval "$@"
