# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias misc='ns:misc'
alias tiktoken='misc:tiktoken'
misc:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAAz2N0QqDMAxF3/cVoQysoMW9TvYl6xBXixY1LW3cKGP/vmww85R7c3Lv9SUwibNY
XTKiEm7gndxMfrbIOmTWbg0+EqScKvjfWrBo4LJrNVrq2PKDw1EWZjk1zdzd+2SLsoUQHZJcLEpG
1A+zkvNUIuZVtP0gSx797UwTd24PiBtCXT8dTXsLhEyTZ9uAFseQteCP9+3wAarkhrLGAAAA
' | zcat | jq
}
misc:tiktoken () 
{ 
    local py='import sys, tiktoken; enc = tiktoken.get_encoding('\''cl100k_base'\''); print(len(enc.encode(sys.stdin.read())))
';
    uv run --with tiktoken python -c "$py"
}
ns:misc () 
{ 
    misc:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f misc:src misc:tiktoken ns:misc
eval "$@"
