# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias misc='ns:misc'
alias fool='misc:fool '
alias utree='misc:utree'
alias md-auto-wrap='misc:md-auto-wrap'
alias list-renamed-claude-sessions='misc:list-renamed-claude-sessions'
alias re-date-ln='misc:re-date-ln'
alias tiktoken='misc:tiktoken'
misc:fool () 
{ 
    local _extglob_state;
    _extglob_state=$(shopt -p extglob);
    shopt -s extglob;
    trap 'eval "$_extglob_state"' RETURN;
    local -n a=MAPFILE;
    mapfile -t < <(declare -f ${1:?});
    ((${#a[*]})) || return 1;
    local i t;
    for ((i = 2; i < $((${#a[*]} - 1)); ++i))
    do
        t=${a[(($i + 1))]};
        printf -v n -- ${t/\%/%%};
        [[ ${#n} == 1 && ${n:(-1)} == "}" ]] || [[ ${#n} == 2 && ${n:(-2)} == "};" ]] && a[$i]+=";";
    done;
    a[-1]+=';';
    a=("${a[@]% }");
    echo "${a[@]##*( )}"
}
misc:list-renamed-claude-sessions () 
{ 
    local jq='select(.display | test("^/rename"))
';
    bajl:self < ~/.claude/history.jsonl
}
misc:md-auto-wrap () 
{ 
    pandoc -f gfm -t gfm --wrap=auto --columns=${1:-80}
}
misc:re-date-ln () 
{ 
    local perl='BEGIN { $j = JSON::PP->new->ascii }
chomp; print $j->encode([ $_, scalar readlink($_) ]), "\n"';
    local jq='map(@sh) | "touch -hr \(last) \(first)"';
    find -maxdepth 1 -type l -print0 | perl -MJSON::PP -0ne "$perl" | bajl:self -r
}
misc:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA41XbW/byBH+3l8xoJWYlEXZzqfCstJLUOeaoskFiQ93gKhKa3IprkUumd2lHdV2
UfQ35OP9uvsl98xStOQiV5xsyNzZ2Xl55tkZenYXaBucBZWyaTAKVIbnvK5LfoZ8FuQimI8CW0Be
1qkoaSG/uFVZXy2sE04m+ul6OghtUTeO4oa2G1GityLbixLtjGjoUN7AYBIM/sdmcEgfLy5//Pg+
0Z3PWJOYvnv14c3bf1wkuhJNrkpJsaNzOg8zmZbCYJnT4O707C8PcBiGg7sDMRvOH6KI7u/JSNca
Tae9QUUu0XltKAwVTenFBJJzGuyOUUynUTShoyMVwV5WJ5rwcdPBnZhBTdERK8wfOnljlHY5xTek
KY4RhztOkmfHz55t92czyA70A02ndErPn2Olz8L4NPKSJHhIAprPOdJ9zRc7zRePmpNOFTtiNlDz
o2kSQMQhalRDzOJTyA4nh3iehsAW8X43f0bwgDxkWtTUCw8OhiFFD3wY5a649Af0o5V5C4D0DYBy
qtYJfpbL5ZWwBdBT1qmMmC10TysjG875zBpeoi7E3EGFeL8TXn+mw7fv/3rxcziezSc0Vlk0ZqVx
lR1SbLxtdnFAr40Ua6VXlAorLcsuC2UJTNEWpap8NATJcKhrR1bkkm4LCWpQqZw0KKuWt6XSEkrg
nKyEdiqlTDhBRrhCGnKF0GQ32okvw+GYfXxqZKpyBVKUm7NEx/Q3aWSc1WlbSe0shcvz84sf3iwj
3nvXlk7F3oV1hmPdema9JBBJoq+SYEm3RjnHkVkSqWt3kXkrr/SG0lrDQps6TgHkldWVzDKZ9YqW
qtY68LYSSj8KOeCPUtha+1AvC0l5q1MPTF4K9gnAIG2EsdLEmmEr1b9gN5O50qqDULuaBBPTIgVc
pLJeMQDEPsY+wrKkLrx2D1ZLVzKtK4ngK2CbkZXwI1xtOP3JMvJn3+YoSF+IK1nWeoWYahpyHYYU
cu1WRsCCiUakHFe0rJFrbTgkAHMjjUPEHCTZRqRyRCnqtmK8+6racUean4rN1kbNBb5VVnpm8O4b
3O/aZEoLsyFbSE7Kl34EjHACv55EyEq0Vp7xmZiWu36yRFkUOCBAuS2iqdC1ZrA8qOC/kRY88dwc
DqnO/X13+4UJX326jFnNqO0xZvMWLE2vcbF6QEZ70DHAAJU4FPm5VWiVcNRjz27AvArJMf5d1XJI
aC9CH9WIjzR1C3OPpON6qXw5oiVCWY7Y2PK2QE9lEV8//vv8OX/f3+O7UY30DIBg4sWTSXfMyEwZ
6RO1EemauN6IIpONhEek3xQb+8guuuJAhFGyK+Alkx8xoMTAshSpr/E3mHerXMHFV2kND5Y87uaG
r0QlheZj3M5xi/ez7O7WritQ0xpZbjoaIOgUQQQPo2/MwCqLRevq+BZzKtjOvwa41ynPmVVe8fTx
f7zKlJXxjOjaStspD6L4zycPv2ee+yg4oUUlsxh0azMZo+lZhhE615+hY2UJYMNxpiyQ2aCXOmkd
Wvo/j7uT6OiRb90+unP69/G4M3UMdoMVm/E1OgVIL8v89wLhXoeRG5dsp5GmhOz1xfdv39MdDa4x
Gv/+6Yf3Z2cfPsQvAWP8UthUKQwTjUFSNZNu8EEzfil1WmcyxPhajMii4MKgpiID9OtwsIhojuuO
WYOyB32KmBjhd7bAiMaOq9u0oLgwlCRhKayL+CFXBk/+iE8TXSyjuBJfwDBQ4hR12DRoYXjh4FBO
YIrToPhdHznFJyg+hh7LMTzvPSB+9nwbE6fWrl5Lj8gGa4XrYzBwNqB/vzch5At4+vV4Jd3CQwAq
hodpeXpysl5gaMrDaItSiPsbQmW8RQr2xtZBf8wwhVG0X832hkzL7xKe+L0XajauwJ2KU5/Pxo/u
b+bQOiNlDzN6P/Eary06QxOJzvjqKggZOv9aUV9dg2xAB61Ld+8sYx5fA2zQfScIuwWt5QZ3nTdx
3Ra82mnsJIR0V67oFPHc68CtX8LtyZ43Ym4E3bMsreyl+xZdDYgdN4/ubSPslRAsVLwnlX3pPXk5
2mYr/c56Xx56RcQQ+mD821533i6YewvM9erpASQ/G6znnRq/uO7vclZPjnJmSOnXr19//fof/OLZ
5+Vlv+zJdNZZRNvC6xmu7R+y2wG2s/jf7bq3pvFGveiq/cTe7rGrhM/j//Og//DdfWQQPz5G7Ffr
6NjfbTp6eizsfewREC/P+xEy8XcH9qv/Bz17x09sdBOy+zxa5z5zXSsdMtW20q3mzmlPQ2xM+P8U
RO3V+5u5bR7Bw/xPvwHy73ZNPQ0AAA==
' | zcat | jq
}
misc:tiktoken () 
{ 
    local py='import sys, tiktoken; enc = tiktoken.get_encoding('\''cl100k_base'\''); print(len(enc.encode(sys.stdin.read())))
';
    uv run --with tiktoken python -c "$py"
}
misc:utree () 
{ 
    local jq='def tree($indent):
  if type == "object" then
    . as $obj |
    ($obj | keys) as $all_keys |
    ($all_keys | length) as $len |
    if $len == 0 then
      ""
    else
      $all_keys | to_entries | map(
        .key as $idx |
        .value as $k |
        ($idx == ($len - 1)) as $is_last_item |
        ($obj[$k]) as $val |
        (if $is_last_item then "└── " else "├── " end) as $connector |
        (if $is_last_item then "    " else "│   " end) as $next_indent |
        (
          if $val | type == "object" then
            "\($indent)\($connector)\($k)/\n" +
            ($val | tree($indent + $next_indent))
          else
            "\($indent)\($connector)\($k)\n"
          end
        )
      ) | join("")
    end
  else
    ""
  end;
tree("")';
    bajl:self -r
}
ns:misc () 
{ 
    misc:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f misc:fool misc:list-renamed-claude-sessions misc:md-auto-wrap misc:re-date-ln misc:src misc:tiktoken misc:utree ns:misc
eval "$@"
