# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias pa='ns:pa'
alias old-test='pa:old-test'
alias parsarg='pa:parsarg'
alias cmpa='pa:cmpa'
alias cmpaa='pa:cmpaa'
alias gen-tests='pa:gen-tests'
alias run-tests='pa:run-tests'
alias check='pa:check'
pa:check () 
{ 
    { 
        echo "${FUNCNAME[1]} ";
        if pa:cmpaa opts ropts && pa:cmpa args rargs && pa:cmpa cont rcont; then
            echo OK;
            declare -p test;
        else
            echo KO;
            declare -p test opts ropts args rargs cont rcont;
        fi
    } | tr -d '\n' | sed 's/declare -[aA]//g';
    echo
}
pa:cmpa () 
{ 
    local -n _a=$1;
    local -n _b=$2;
    [[ ${#_a[@]} -ne ${#_b[@]} ]] && return 1;
    for ((i=0; i<${#_a[@]}; i++))
    do
        [[ "${_a[i]}" != "${_b[i]}" ]] && return 1;
    done;
    return 0
}
pa:cmpaa () 
{ 
    local -n _a=$1;
    local -n _b=$2;
    [[ ${#_a[@]} -ne ${#_b[@]} ]] && return 1;
    for k in "${!_a[@]}";
    do
        [[ -v _b[$k] ]] || return 1;
        [[ "${_a[$k]}" != "${_b[$k]}" ]] && return 1;
    done;
    return 0
}
pa:gen-tests () 
{ 
    local macros='{"empty":{"test":[],"opts":[],"args":[],"cont":[]}}';
    local tests='[{"tags":["empty"],"test":[],"opts":[],"args":[],"cont":[]},{"tags":["single","mark"],"opts":[],"args":[],"cont":[],"test":["--"]},{"tags":["single","mark"],"opts":[],"args":[],"cont":[],"test":["++"]},{"tags":["dual","mark"],"opts":[],"args":[],"cont":[],"test":["--","++"]},{"tags":["dual","mark"],"opts":[],"args":[],"test":["++","--"],"cont":["--"]},{"tags":["single","arg"],"opts":[],"cont":[],"test":["a"],"args":["a"]},{"tags":["dual","arg"],"opts":[],"cont":[],"test":["a","b"],"args":["a","b"]},{"tags":["single","opt"],"args":[],"cont":[],"test":["-x"],"opts":["x",1]},{"tags":["dual","opt"],"args":[],"cont":[],"test":["-x","-y"],"opts":["x",1,"y",1]},{"tags":["opt","arg"],"args":[],"cont":[],"test":["-x","a"],"opts":["x","a"]},{"tags":["opt","eq"],"args":[],"cont":[],"test":["--x=a"],"opts":["x","a"]},{"tags":["opt","arg"],"args":[],"cont":[],"test":["-x","a","b"],"opts":["x","a b"]},{"tags":["opt","eq"],"cont":[],"test":["--x=a","b"],"opts":["x","a"],"args":["b"]}]';
    local jq='def body:
  [ "local -A opts=()", "local args=()", "local cont=()" ]
	+ [ "local test=(\(.test))", "local -A ropts=(\(.opts))", "local rargs=(\(.args))", "local rcont=(\(.cont))" ]
	+ [ "parsarg \"${test[@]}\"", "check" ]
  | join("; ");
$tests | map(map_values(map(@sh) | join(" ")))
  | [ keys, map(.) ] | transpose | map ({ name: "pa:test\(100 + first)" } + last)
  | map("\(.name) () { \(body); }")[]';
    bajl:self -nr --argjson tests "$tests"
}
pa:old-test () 
{ 
    local -A k;
    local t;
    function pa:add () 
    { 
        t+=("$1");
        k["$1"]="$2"
    };
    pa:add 'pa:try' 'declare -a input=() declare -A opts=() declare -a args=() declare -a cont=()';
    pa:add 'pa:try --' 'declare -a input=([0]="--") declare -A opts=() declare -a args=() declare -a cont=()';
    pa:add 'pa:try ++' 'declare -a input=([0]="++") declare -A opts=() declare -a args=() declare -a cont=()';
    pa:add 'pa:try -- ++' 'declare -a input=([0]="--" [1]="++") declare -A opts=() declare -a args=() declare -a cont=()';
    pa:add 'pa:try ++ --' 'declare -a input=([0]="++" [1]="--") declare -A opts=() declare -a args=() declare -a cont=([0]="--")';
    pa:add 'pa:try a' 'declare -a input=([0]="a") declare -A opts=() declare -a args=([0]="a") declare -a cont=()';
    pa:add 'pa:try a b' 'declare -a input=([0]="a" [1]="b") declare -A opts=() declare -a args=([0]="a" [1]="b") declare -a cont=()';
    pa:add 'pa:try a b -x' 'declare -a input=([0]="a" [1]="b" [2]="-x") declare -A opts=([x]="1" ) declare -a args=([0]="a" [1]="b") declare -a cont=()';
    pa:add 'pa:try -x -- a b' 'declare -a input=([0]="-x" [1]="--" [2]="a" [3]="b") declare -A opts=([x]="1" ) declare -a args=([0]="a" [1]="b") declare -a cont=()';
    pa:add 'pa:try -xx -- a b' 'declare -a input=([0]="-xx" [1]="--" [2]="a" [3]="b") declare -A opts=([x]="2" ) declare -a args=([0]="a" [1]="b") declare -a cont=()';
    pa:add 'pa:try -xx --y z -- a b' 'declare -a input=([0]="-xx" [1]="--y" [2]="z" [3]="--" [4]="a" [5]="b") declare -A opts=([y]="z" [x]="2" ) declare -a args=([0]="a" [1]="b") declare -a cont=()';
    pa:add 'pa:try -xx --y z -- a b -u a s d -v' 'declare -a input=([0]="-xx" [1]="--y" [2]="z" [3]="--" [4]="a" [5]="b" [6]="-u" [7]="a" [8]="s" [9]="d" [10]="-v") declare -A opts=([y]="z" [x]="2" ) declare -a args=([0]="a" [1]="b" [2]="-u" [3]="a" [4]="s" [5]="d" [6]="-v") declare -a cont=()';
    pa:add 'pa:try -xxy a' 'declare -a input=([0]="-xxy" [1]="a") declare -A opts=([y]="a" [x]="2" ) declare -a args=() declare -a cont=()';
    for i in "${t[@]}";
    do
        r=$($i) e="${k["$i"]}";
        [ "$r" == "$e" ] && echo -n 'OK ' || echo -n 'KO ';
        echo "$e";
    done
}
pa:parsarg () 
{ 
    shopt -q extglob || { 
        shopt -s extglob;
        trap 'shopt -u extglob' RETURN
    };
    local -a tmp;
    local opt next ctx;
    local state=START;
    local END='@(-[!0-9]*|)';
    local ARG='!(++)';
    local VAL='@(-|[!-]*|-[0-9]*)';
    local NUM='-[0-9]*';
    local ANY='*';
    local CONT=++;
    local ARGS=--;
    local SHORT='-[!-]*';
    local LONG='--*';
    local ASSIGN='@(--*=*|-[!0-9]*=*)';
    until [[ $# -eq 0 ]]; do
        [[ -n "$debug" ]] && echo $# "$@";
        if [[ "$2" == $END ]]; then
            next=END;
        else
            if [[ "$2" == $VAL ]]; then
                next=VAL;
            else
                next=ERROR;
            fi;
        fi;
        ctx="$state^$1^$next";
        [[ -n "$debug" ]] && echo "$ctx";
        if [[ "$ctx" == $ANY^$ANY^ERROR ]]; then
            do=ERROR;
        else
            if [[ "$ctx" == $ANY^$CONT^$ANY ]]; then
                do=CONT;
            else
                if [[ "$ctx" == $ANY^$ARGS^$ANY ]]; then
                    do=NEXT state=ARGS;
                else
                    if [[ "$ctx" == START^@($VAL|$NUM)^$ANY ]]; then
                        do=ARG;
                    else
                        if [[ "$ctx" == ARGS^$ARG^$ANY ]]; then
                            do=ARG;
                        else
                            if [[ "$ctx" == @(START|OPT)^$ASSIGN^$ANY ]]; then
                                do=ASSIGN state=START;
                            else
                                if [[ "$ctx" == @(START|OPT)^$SHORT^$ANY ]]; then
                                    do=SHORT state=START;
                                else
                                    if [[ "$ctx" == START^$LONG^END ]]; then
                                        do=LONG-END;
                                    else
                                        if [[ "$ctx" == START^$LONG^VAL ]]; then
                                            do=LONG-VAL state=OPT;
                                        else
                                            if [[ "$ctx" == OPT^$ANY^VAL ]]; then
                                                do=OPT-VAL;
                                            else
                                                if [[ "$ctx" == OPT^$ANY^END ]]; then
                                                    do=OPT-VAL state=START;
                                                else
                                                    do=ERROR;
                                                fi;
                                            fi;
                                        fi;
                                    fi;
                                fi;
                            fi;
                        fi;
                    fi;
                fi;
            fi;
        fi;
        case $do in 
            "")
                :
            ;;
            CONT)
                shift;
                cont=("$@");
                shift $#
            ;;
            NEXT)
                shift
            ;;
            ARG)
                args+=("$1");
                shift
            ;;
            SHORT)
                tmp=();
                opt="${1:1}";
                shift;
                for ((i=0; i < ${#opt}; i++))
                do
                    tmp+=("--${opt:i:1}");
                done;
                set -- "${tmp[@]}" "$@"
            ;;
            ASSIGN)
                opt="${1%%=*}";
                val="${1#*=}";
                opt="${opt##+(-)}";
                opts["$opt"]="$val";
                shift
            ;;
            LONG-END)
                opt="${1:2}";
                opts["$opt"]=$((opts["$opt"] + 1));
                shift
            ;;
            LONG-VAL)
                opt="${1:2}";
                opts["$opt"]="$2";
                shift 2
            ;;
            OPT-VAL)
                opts["$opt"]+=" $1";
                shift
            ;;
            ERROR | *)
                { 
                    echo $# "$@";
                    declare -p do state next
                } | fmt -999;
                shift
            ;;
        esac;
        [[ -n "$debug" ]] && declare -p opts args cont;
    done
}
pa:run-tests () 
{ 
    source <(gen-tests);
    source <(compgen -c pa:test)
}
pa:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA71ZbXPaSBL+fr+iLbSLZNDG+F4NUZWprNebSgxb2Lm7LQm7BAxGAUtEEo5ZzH+/
7h5JSEJgJ2sfVYaZnu6nn57pmR7J1krxQqWpzB2lrrgjbgWhE9xiN5xgtwJh5EQiNLXLq3bvCtq9
80vo/nYFarvzu257yfjN3IkiEXiomI4MF0EgvOgG4bLD/25/ROveOUOA+q7bueL+JaiXv3bRh/qx
26HRy8v35x1G8sTDFsxZ52cgrLxCtJwTWRqUfiQX0vn5lzaSXc4E2Ip6aitAobreLWhf3WgCgXBG
4EzwmxEvnGg4AU3l8Opk0rCVOqjkSYfIh5EYuiMBXydOxF0f/HGsZnu2F078eQTGF0D925k/gMdH
WEEsDRNpC6LAmUM1li8SeRV6Z1efep0WrG1v5g+dGRgORHfzpEfqRAWG0UMiY6omrxMxwIjF2PXc
yPW9MNHBiTGrp5phHRwZJ/3DR70KyRAugVk90Gq1jAznkNUfrQMDtQ2LrTIKnU8XZjUWZ6A6v5vV
TJ/W2KzVsq4uTcNI+7zuhENeNmaUByg1DqsUTUd8hd/k+jfl8ogQDGNq3oMfAP3WYbCIwL31/ICG
GjiieYu7UE/9ckpxRMahSfHIaTAxJJqyhRe5M7AsUCtgiC9wBP1+C5fW9gA/KMf1HYnB4hazp9+H
H38EMZz4pC1TSurJ7wp89P0pJxS2bt2hFLvjFOkYUUwTOJPJTzQRHi+qiZKWVBczNMirU17n1VGS
qocihuj1ur0WjN0sJ0wWE5E4Ua7VxjVnc0J7Z3gopSzjtC6EwHJmhUt+zV/seEMw8xn5Maut0Aow
lC4MtguGFJ5EoSTbi9I5+++V7MidQwZ7UHljXZ/yAfaoYuLr2+iIiih7QGJSvfPdzPIgSTIZuF06
Z/+JU/jiDA/Nq167c/n+6n23Q6OJ4sUixFPBvxMwEGPcCHJzveEzFc+pIZ9r6BNpYS5gPxS76Z7K
Y/8RT3yKln0XmRNdHtjMJBu1IEmYp5GZ49aUILKsCEXkpxaJK8h1bl/l55fGjdJdVoqU23IlSDQe
E8R49oDiqNwlCSJ+SkBRzchu6j1ASZB7gXZMH54V3/xJN3HxaME8AhWroBsvOg8ptqJDs9XaiGjr
6lgH3XHUwjT1IlOTZ6feklI8TbP6tEkT/YwYN4gOWPDDGts3NvZZLc4e3c7NChZRU0NlrKB0Fq4a
zcbaVhLjvC7uH9A01zxqgQtvQV1V0GqNHSySOhUGQmMGhqGucKzpMhqPeaKAFgos8QYt4wrNrNM+
asaFI0t60yrd9e13+R3Ps5FclbLu0gB/+ME8JFcx5jnSmIolYA3En4LRvTOTRpVDM7WJjXBsIUDD
nx2e8LdSqWmGzpYVeDcTjgcjJ6RKrW07Q/3QQkP8tZU+QSA2mlagHYZYxgvTl6zuRpxsYz2zmse8
mgVoVdPyEqhBQy9LmWQ/PwkpK3KStMdZjHjX6QWTGp23lKolbnlPPR7qeEfMXyladNGcOXiOG3NK
ON7HXOLxbgiPML7DpDo5OcknsAid4e6qnkEkhryPeC/aHqWtsq5vPRYM77jNzwTxfdSDG8dUGy3Y
9AcmzolH96dV5cahDEex4N6Ae9J/IKJF4EHD9rIb7G1qlNlg2SBWOOrypjkwZX8Q94uwFIXtxf2j
XfG8VkBTPAOZ34E04UXESOwIgYx7RLXUaZ9M8ZlgY5oPFDXykcaC7wh1IobTJNRVeqVb/fKp867T
vjizGhgHciQGWGh4ZmReBPyN7kgmsyTg70REOQOBzJy4/jB890MubfH5kBW44rDCh+6WQtZlxlXe
xdiVWR/hhX8EVdv2qtgLBbbDNymg5bT7b97cVlvsrGxOboVnkNMQBXfOMPBxeKWIu3m0pAYNKU2r
X1eIjmwRG9kiMtRar+uKBGlaaOPweAzSrz8XpL4xpafRmWBKwVR5wjB1gLVHeQmYWi0PM1o4s+/h
Uv8epAyJOgeUgu8Oj15T5OC26TjKxgt1Slg9C6WuDPJILChlhUDKU5P0kPGoPCj1Rhmx5wHhbC2L
aHVlWcQksDTWJyGdAmJx6iSa+PIkmPFgPg/r+czipcghwmA3v12synCya0yQ2P38BY+LkRjDwB8t
m3QG0REdV4g2H1p4naRXQ4mUAAoiec/V6fimMlDLYBApvEDa2k/U0nNmiB9IBzROrfx4IF3RILUK
g/HlGgeppRe8x+/5wLb5Poq+uVTZdGUnEK4a0gTwiP3su55GhYwut7an8rmH8jtnruHfDd8NQ2pq
p+FE31iQga5LEIvunWGdjX7Soc8HueOFcx/rAmOBtgLPuRNNZtjkwmFrjaMjvK+N3QAnCBHX2Jk5
1GZUQkPWGCdZ6qDRJQq7tGA6vUBTdKuf1L9QzMZYwrF8GBj959D3QIaCs8ANxC8rGMFiUzAkkL8I
hgLeamkpQTqpEJ+/5zgAxhDiMPQyVH82YtvCRaQN0+QSglUPAZzRSIYVZR93ppZsbu6i61S7Sm6D
ZRWqaVV08FoyX1AebkpvmsCQUYsTOCuKE7haxMdpLHVhHREpfERRXtJZrbbHWa32ss7wyWuvPwoO
8O70Cq5rtf3zSv5i139qijOrtE3C2UPAea7TMvU9geNBvt9rHPXgm/2XGu5nAsbDc8mAdcwz+VDK
y3qgQdyo8JIMjQdK0f0zRoQyiRLTZGd/3T2Pr8X3WYT/BOPjV2G8hD++lfcyJf5HSlxG87eUyt/3
RLNMTf8vcdH/nRwIYYQPp68SI1j/4OEFNf+ZDv+LWlRwrRNqjRhdurp/4YlJNugi5eqkVMOU6mhD
9f4bJnP/WUkKKZXyg1PG5TwV1w5C9MrBTV45RPkXDoGpaqqrg+A3WXxhcPHCsOZ/5kQV+arJbcXv
nIKkIfhlBQEG8nUztgRdBtP/CRkeVLsfoEqvMFLBhy7Ez9yxQfI+qf+X/wG1NvBFaR4AAA==
' | zcat | jq
}
ns:pa () 
{ 
    pa:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f pa:check pa:cmpa pa:cmpaa pa:gen-tests pa:old-test pa:parsarg pa:run-tests pa:src ns:pa
eval "$@"
