# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias path='ns:path'
alias delp='path:delp'
alias addp='path:addp'
path:addp () 
{ 
    local jq='(env.PATH / ":") as $p | ($ARGS.positional - $p) + $p | join(":")';
    : ${1:?};
    PATH=$(self -nr --args "$@")
}
path:delp () 
{ 
    local jq='(env.PATH / ":") as $p | $p - $ARGS.positional | join(":")';
    : ${1:?};
    PATH=$(self -nr --args "$@")
}
path:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA62OMQvCMBCFd3/FcWRIsam4RkQ76SjqZh0CiW1KSGJTXGr/uyfdOjm4HB+8947v
NmBqUKIENqzlbtzAqbwet4wn4x4gfAdCqK5OUCHbV5hhjj5RP6q+IbaaWGkdidsnMTf+VXxfwIom
khagErAIb+CsPB8uRQzJ9jZ45UBQkMFyittgPZ8mOOZ/0NLG/aJFhzzmajOf++IDCaIlNykBAAA=
' | zcat | jq
}
ns:path () 
{ 
    path:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f path:addp path:delp path:src ns:path
eval "$@"
