# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias path='ns:path'
alias delp='path:delp'
alias addp='path:addp'
path:addp () 
{ 
    local jq='(env.PATH / ":") as $p | ($ARGS.positional - $p) + $p | join(":")';
    : ${1:?};
    PATH=$(jq "$jq" -nr --args "$@")
}
path:delp () 
{ 
    local jq='(env.PATH / ":") as $p | $p - $ARGS.positional | join(":")';
    : ${1:?};
    PATH=$(jq "$jq" -nr --args "$@")
}
path:src () 
{ 
    base64 -d <<< 'H4sIAAAAAAAAA62OPQvCMBBAd3/FcWRIsam4RkQ76SjqZh0CKTah5KMpLrX/3SvdOjm4HI873vEe
A6YGJUpgw1Yexh1cyvt5z7iNUCGzsUIQrgMhVPdK0+pYYYY5ukRWUH1DbDSx0joQ20jMa/cupkew
IUWSASoBC/ABzsrr6VYEn0xvvFMtCDpksJ7P1hvHZwXH/G9xum5/iaNBNcvARdVz9QWr22MFNQEA
AA==
' | zcat | jq
}
ns:path () 
{ 
    path:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f path:addp path:delp path:src ns:path
eval "$@"
