# generated by bajl:as-lib, avoid edit
shopt -s expand_aliases
alias path='ns:path'
alias delp='path:delp'
alias addp='path:addp'
path:addp () 
{ 
    local jq='(env.PATH / ":") as $p | ($ARGS.positional - $p) + $p | join(":")';
    : ${1:?};
    PATH=$(self -nr --args "$@")
}
path:delp () 
{ 
    local jq='(env.PATH / ":") as $p | $p - $ARGS.positional | join(":")';
    : ${1:?};
    PATH=$(self -nr --args "$@")
}
path:src () 
{ 
    jq <<< '[{"sh":": ${1:?}; PATH=$(self -nr --args \"$@\")","ns":"path","id":"addp","jq":"(env.PATH / \":\") as $p | ($ARGS.positional - $p) + $p | join(\":\")"},{"sh":": ${1:?}; PATH=$(self -nr --args \"$@\")","ns":"path","id":"delp","jq":"(env.PATH / \":\") as $p | $p - $ARGS.positional | join(\":\")"}]'
}
ns:path () 
{ 
    path:${1:?} "${@:2}"
}
bajl:self () 
{ 
    jq "$jq" "$@"
}
export -f path:addp path:delp path:src ns:path
eval "$@"
